services:
  #######################################################
  # go-interview-challenge
  #######################################################
  go-interview-challenge:
    image: cosmtrek/air:latest
    working_dir: /code
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_SSL_MODE: disable
      POSTGRES_HOST: postgres
      KAFKA_BROKER_HOSTS: kafka:29092
      KAFKA_REGISTRY_URL: http://kafka:8081
      KAFKA_CONSUMER_GROUP_ID: go-interview-challenge
    volumes:
      - ./:/code
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - local

  #######################################################
  # Postgres
  #######################################################
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - PGSSLMODE=disable
    healthcheck:
      test: pg_isready -U postgres -d postgres
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - local

  #######################################################
  # Liquibase
  #######################################################
  liquibase:
    image: liquibase/liquibase:4.9.1
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./liquibase/changelogs/changelog.yaml:/liquibase/changelogs/changelog.yaml
      - ./liquibase/liquibase.properties:/liquibase/liquibase.properties
    # entrypoint: sh -c 'tail -f /dev/null'
    command: --defaults-file=/liquibase/liquibase.properties update
    networks:
      - local

  #######################################################
  # Kafka
  #######################################################
  kafka:
    image: redpandadata/redpanda:latest
    command:
      - redpanda start
      - --smp 1
      - --overprovisioned
      - --node-id 0
      - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://kafka:29092,OUTSIDE://localhost:9092
      - --pandaproxy-addr 0.0.0.0:8082
      - --advertise-pandaproxy-addr localhost:8082
    ports:
      - 8081:8081
      - 8082:8082
      - 9092:9092
      - 9644:9644
      - 29092:29092
    networks:
      - local

networks:
  local:
    name: go-interview-challenge-net
